name: "roads-segmentation"
platform: "tensorrt_plan"

max_batch_size: 1

input [
  {
    name: "raw_image"
    data_type: TYPE_UINT8      # если вы патчили вход на UINT8→FP32, укажите FP32
    dims: [3, -1, -1]
  }
]

output [
  {
    name: "binary_mask"
    data_type: TYPE_FP32      # или TYPE_FP32, смотря что реально внутри вашего TensorRT-движка
    dims: [-1, -1, -1]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]
