MODEL_NAMES = ["mini_unet", "large_unet"]
DUMMY_INPUT_ONNX_SHAPE = (1, 3, 400, 400)
PIXEL_MIN = 0
PIXEL_MAX = 255
ONNX_MODEL_NAME = "model_full.onnx"
ONNX_INPUT_NAME = "raw_image"
ONNX_OUTPUT_NAME = "binary_mask"
ONNX_OPSET_VERSION = 13
HYDRA_OUTPUT_DIR = "outputs"
CKPT_FILE_NAME = "last.ckpt"
TRT_MIN_SHAPE = "1x3x1x1"
TRT_OPT_SHAPE = "1x3x400x400"
TRT_MAX_SHAPE = "1x3x1024x1024"
PBTXT_CONFIG_NAME = "config.pbtxt"
ONNX_PBTXT_CONFIG_NAME = "config_onnx.pbtxt"
TRT_PBTXT_CONFIG_NAME = "config_trt.pbtxt"
TRITON_ONNX_MODEL_FILENAME = "model.onnx"
TRITON_TRT_MODEL_FILENAME = "model.plan"
TRITON_REPO_DIRNAME = "triton_repo"
TRITON_MODEL_NAME = "roads-segmentation"
DATA_DIR = "data"
DATASET_DIR = "dataset"
TRAIN_DIR = "training"
IMAGES_DIR = "images"
GROUND_TRUTH_DIR = "groundtruth"
PIPELINE_PICTURE_SIZE = (400, 400)
