defaults:
  - _self_
  - datamodule: road_data
  - model: large_unet
  - mlflow_logger: mlflow
  - plots_logger: csv
  - callback: plot_metrics

trainer:
  accelerator: auto
  devices: 1
  max_epochs: 1
  log_every_n_steps: 5
  fast_dev_run: false
